language: python
python:
- 3.7
- 3.6

before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
install: 
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
script: pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scientanalytics
  password:
    secure: SsUAGV7z5uxOT5avqFDOeZeTGKijhMEg/mlDzUq6brsQGfktyhx7UHsqNOJs40sjcT7QJpfFsNlxnuC1XeZM+cZZnQtP8gBcK3J2F3LckF9dogFaIQmC1w9xVWydLTf5M/tysoBUdBPyI3HdiRSlLGYBHAFilrbugKt7SAxoVnloAMRWj7m7hVkHu+73Ny8rpLtrfTNiMEr6sZIArVhGyvojEPGJiZPkrH2SMUj9osLTULzpoF0rClH/aNi1QX9biDnkuqKH+4HbfWBaa4/OlRrPkq9hp4msXTxzfEzyySLUdjGQUq2iWXNqrXtzz7fcoFKMmOFLWbulyGG3vLi6aDeP/wWTL3/aVpSldmemb3tvbatq7ImWgmeZxnFEHQmyL1zBq2Vd6L1hBzI7UiJgez1gjkLma/PwjcBqYN7TF7MdyWkK1zMpaOLPdNYh/Z0lgflFsDKfNO1qwU2WGtUyFuKTtanER28AjLQ6v7r5fzTNOy1BEjrhAcr9+ULYxKCxEwR7gGcHnA8pFzjGb1dGWZbfrb3wgJcUA3tPgrTRJTWEawGpzp/OeDvPjeVW9Z/PCrk0Qe6/UygCVS8PxXufiXslmbKR9CvllPjMPNaJ5mK4XwDWCGHVXkHk/obxED9LI3qRAnDyf3/QkFjlP/6g+zJHtL2uzLjc1OBXfU/hTm4=
  on:
    tags: true
    repo: scientanalytics/ml_studio
    python: 3.7
after_success:
- codecov
