language: python
python:
- 3.7
- 3.6
- 3.5
before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
script: 
- pytest --cov-report term --cov=ml_studio
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: decisionscients
  password:
    secure: FBFouxUhXaaAJ1VE0dM91W+L6/a0zl2HuY71xFg46ylavv9gmimiy7m+02Mpcax/YotKGuZixlEMEgRuAxATuKs3Du2HKP2Sczuui9qC4xDBILMCmqgLRK2g2z8cvzmf0F3ogNyBeulMGsSPd12xsfBWekh9LU/LKpX1SPjRYX64kILHS1+Q2f2ljFR3hYFSh6aWJM9HsxrQv0aDahYzZKS0ql48MJ/ADIy1aNDKUs9I7Swi4ehrCmanLqbG7IJszTJreji00nbmuam1sXyOs3PQaWQaUZ6e63jfnxaY/R+O2p7rFBV7aK9ncAfF3bhPV5cBIxq1lFEpFDyBYYpTUnIvSCT1CxGOFJ+78k8csNLJXQeZqdcRFgkJyRRFSrokCrQwjSm18yc0eIjiuwl5uTNegWr3t68N9OoHVNAM84aBnNdY0KpUhWQfYz80AgDQEbha0tRM4ocNmp7famSHV2DfnoxeCdimMLJYiGeHmrx17ue0s+oG4+XFQM2QPCfRjrT0fdftBtuRAdnf/f6h3QxJbWaFUIusX4c+ccjJnCMeMJw8ekXkXlZKy+CT6c4to4/aSAxUOJbgGeJ0polpd62lrhYtdmY2E77wlCjHyet0wF0+bINsjIpqiNMjAATMuaXtcO+24VSut9ef64pP78CwPViCYGjs6Rd4oUE7rhc=
  on:
    branch: master
    repo: ml-studio
    python: 3.7
after_success:
- codecov
